CONTAINER Osnoot
{
	NAME Osnoot;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL SNOOT_LENGTH      { UNIT METER; MIN 0.0; STEP 1.0; CUSTOMGUI REALSLIDER; MINSLIDER 0.0; MAXSLIDER 500.0; }
		REAL SNOOT_OPENING_X   { UNIT PERCENT; MIN 1.0; MAX 1000.0; STEP 1.0; CUSTOMGUI REALSLIDER; MINSLIDER 10.0; MAXSLIDER 200.0; }
		REAL SNOOT_OPENING_Y   { UNIT PERCENT; MIN 1.0; MAX 1000.0; STEP 1.0; CUSTOMGUI REALSLIDER; MINSLIDER 10.0; MAXSLIDER 200.0; }
		REAL SNOOT_ROUNDNESS   { UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 1.0; CUSTOMGUI REALSLIDER; MINSLIDER 0.0; MAXSLIDER 100.0; }
		SEPARATOR { LINE; }
		REAL SNOOT_THICKNESS   { UNIT METER; MIN 0.01; STEP 0.1; }
		LONG SNOOT_SUBDIVISION { MIN 1; MAX 64; }
	}

	GROUP SNOOT_GROUP_FIT
	{
		DEFAULT 1;

		STATICTEXT SNOOT_INFO { }
		LONG SNOOT_SIZE_MODE
		{
			CYCLE
			{
				SNOOT_SIZE_MODE_LIGHT;
				SNOOT_SIZE_MODE_MANUAL;
			}
		}
		REAL SNOOT_SIZE_X  { UNIT METER; MIN 0.0; STEP 1.0; }
		REAL SNOOT_SIZE_Y  { UNIT METER; MIN 0.0; STEP 1.0; }
		SEPARATOR { LINE; }
		REAL SNOOT_PADDING { UNIT METER; MIN 0.0; STEP 0.1; }
		REAL SNOOT_OFFSET  { UNIT METER; STEP 1.0; }
		BOOL SNOOT_FLIP    { }
	}

	GROUP SNOOT_GROUP_RENDER
	{
		DEFAULT 1;

		LONG SNOOT_RENDERER
		{
			CYCLE
			{
				SNOOT_RENDERER_AUTO;
				SNOOT_RENDERER_REDSHIFT;
				SNOOT_RENDERER_ARNOLD;
				SNOOT_RENDERER_OCTANE;
				SNOOT_RENDERER_STANDARD;
			}
		}
		BUTTON SNOOT_SETUP_RENDER { }
	}
}
